---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: scheduler-
namespace: scheduler
resources:
  - k8s-deployment-nginx-with-custom-scheduler.yaml
  - k8s-deployment-nginx.yaml
