---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nlb-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-nlb
  template:
    metadata:
      labels:
        app: nginx-nlb
    spec:
      containers:
        - name: nginx-nlb
          image: nginx
          ports:
            - name: http
              containerPort: 80
