---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: listener-port-
namespace: load-balancers
resources:
  - k8s-deployment.yaml
  - k8s-ingress.yaml
  - k8s-service.yaml
configurations:
  - kustomizeconfig.yaml
