apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k8s-namespace.yaml
  - k8s-deployment-sample-app.yaml
  - k8s-service.yaml
  # Note: k8s-targetgroupbinding.yaml is not included here because it needs variable substitution
