apiVersion: v1
kind: Namespace
metadata:
  name: scenario-workload-id
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gcp-access
  namespace: scenario-workload-id
  annotations:
    iam.gke.io/gcp-service-account: ${GCP_SERVICE_ACCOUNT}
---
apiVersion: v1
kind: Pod
metadata:
  name: gcp-client
  namespace: scenario-workload-id
spec:
  serviceAccountName: gcp-access
  containers:
    - name: gcloud
      image: gcr.io/google.com/cloudsdktool/google-cloud-cli:slim
      command: ["sleep", "3600"]
